MiniStore/MiniStore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

MiniStore/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart', views.CartView.as_view(), name = 'cart'),
    path('add-to-cart/<int:product_id>', views.add_to_cart, name = 'add_to_cart')
]

MiniStore/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='products'),
    path('<int:pk>', views.ProductDetailView.as_view(), name='product'),
    path('add-product', views.ProductCreateProduct.as_view(), name='add_product')
]

MiniStore/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register')
]

MiniStore/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


# Create your models here.


class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def total_price(self):
        return self.quantity * self.product.price


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)

    def total_price(self):
        return sum([item.total_price() for item in self.items.iterator()])

    @staticmethod
    def get_current_order(user):
        qs = Order.objects.filter(user__id=user.id, ordered=False)
        if qs:
            return qs[0]

MiniStore/products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=100)
    short_description = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    price = models.FloatField()

MiniStore/users/models.py
from django.db import models

# Create your models here.

MiniStore/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

MiniStore/orders/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from orders.models import Order, OrderItem
from products.models import Product
from django.views.generic import TemplateView


# Create your views here.

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    order_item, created = OrderItem.objects.get_or_create(product=product, user=request.user, ordered=False)
    order = Order.get_current_order(request.user)
    if order:
        if order.items.filter(product__id=product_id).exists():
            order_item.quantity += 1
            order_item.save()
        else:
            order.items.add(order_item)
    else:
        order = Order.objects.create(user=request.user)
        order.Items.add(order_item)
    return redirect('products:products')



class CartView(TemplateView):
    template_name = 'orders/cart.html'

    def get_context_data(self, **kwargs):
        current_order = Order.get_current_order(self.request.user)
        total_price = current_order.total_price()
        shipping = 15
        return {
            'order': current_order,
            'total_price': total_price,
            'shipping': shipping,
            'total_price_with_shipping': total_price + shipping
        }

MiniStore/products/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Product
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView
from django.urls import reverse_lazy


# Create your views here.
def homepage(request):
    return HttpResponse('hello')


class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'products.html'

    def get_queryset(self):
        return Product.objects.all()


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'product.html'


class ProductCreateProduct(PermissionRequiredMixin, CreateView):
    model = Product
    fields = '__all__'
    template_name = 'products_form.html'
    success_url = reverse_lazy('products:products')
    permission_required = ('products.add_product',)

MiniStore/users/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import FormView
from .forms import RegisterForm



# Create your views here.
class MyLoginView(LoginView):
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('products:products')

    def form_invalid(self, form):
        messages.error(self.request, 'invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))

class RegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('products:products')
    def form_valid(self, form):
        user = form.save()
        if user:
            login(self.request, user)
            return super(RegisterView, self).form_valid(form)

MiniStore/orders/templates/orders/cart.html
{% extends "main.html" %}

{% block content %}

    {% if order %}
        <section class="h-100 gradient-custom">
            <div class="container py-5">
                <div class="row d-flex justify-content-center my-4">
                    <div class="col-md-8">
                        <div class="card mb-4">
                            <div class="card-header py-3">
                                <h5 class="mb-0">Cart - {{ order.items.all | length }} items</h5>
                            </div>
                            <div class="card-body">
                                {% for item in order.items.all %}
                                    {% with product=item.product %}
                                        <div class="row">
                                        

                                            <div class="col-lg-6 col-md-6 mb-4 mb-lg-0">
                                                <!-- Data -->
                                                <p><strong>{{ product.title }}</strong></p>
                                                <p>{{ product.short_description }}</p>
                                                <p>{{ product.description }}</p>
                                                <button type="button" class="btn btn-primary btn-sm me-1 mb-2"
                                                        data-mdb-toggle="tooltip"
                                                        title="Remove item"
                                                        onclick="location.href=''">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                                <button type="button" class="btn btn-danger btn-sm mb-2"
                                                        data-mdb-toggle="tooltip"
                                                        title="Move to the wish list">
                                                    <i class="fas fa-heart"></i>
                                                </button>
                                                <!-- Data -->
                                            </div>

                                            <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                                                <!-- Quantity -->
                                                <div class="d-flex mb-4" style="max-width: 300px">
                                                    <button class="btn btn-primary px-3 me-2"
                                                            onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                                        <i class="fas fa-minus"></i>
                                                    </button>

                                                    <div class="form-outline">
                                                        <input id="form1" min="0" name="quantity"
                                                               type="number"
                                                               class="form-control" value="{{ item.quantity }}"/>
                                                        <label class="form-label" for="form1">Quantity</label>
                                                    </div>

                                                    <button class="btn btn-primary px-3 ms-2"
                                                            onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                                                        <i class="fas fa-plus"></i>
                                                    </button>
                                                </div>
                                                <!-- Quantity -->

                                                <!-- Price -->
                                                <p class="text-start text-md-center">
                                                    <strong>{{ item.total_price }} lei</strong>
                                                </p>
                                                <!-- Price -->
                                            </div>
                                        </div>
                                        <hr class="my-4"/>
                                    {% endwith %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-body">
                                <p><strong>Expected shipping delivery</strong></p>
                                <p class="mb-0">12.10.2020 - 14.10.2020</p>
                            </div>
                        </div>
                        <div class="card mb-4 mb-lg-0">
                            <div class="card-body">
                                <p><strong>We accept</strong></p>
                                <img class="me-2" width="45px"
                                     src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                                     alt="Visa"/>
                                <img class="me-2" width="45px"
                                     src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                                     alt="American Express"/>
                                <img class="me-2" width="45px"
                                     src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                                     alt="Mastercard"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <div class="card-header py-3">
                                <h5 class="mb-0">Summary</h5>
                            </div>
                            <div class="card-body">
                                <ul class="list-group list-group-flush">
                                    <li
                                            class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                                        Products
                                        <span>{{ total_price }} lei</span>
                                    </li>
                                    <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                        Shipping
                                        <span>{{ shipping_tax }}</span>
                                    </li>
                                    <li
                                            class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                                        <div>
                                            <strong>Total amount</strong>
                                            <strong>
                                                <p class="mb-0">(including VAT)</p>
                                            </strong>
                                        </div>
                                        <span><strong>{{ total_price_with_shipping }} lei</strong></span>
                                    </li>
                                </ul>

                                <button type="button" class="btn btn-primary btn-lg btn-block">
                                    Go to checkout
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {# Add buy button #}
    {% else %}
        <div class="container">
            <p>No products in the cart</p>
        </div>
    {% endif %}
{% endblock %}

MiniStore/products/templates/product.html
{% extends "main.html" %}

{% block content %}

    <div class="card mb-5 mt-4" style="width: 18rem; height: 20rem;">
        <div class="card-body d-flex flex-column">
            <h5 class="card-title">{{ product.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ product.short_description }}</h6>
            <p class="card-text" style="height: 10vh; overflow: hidden">{{ product.description }}</p>
            <p class="card-text">{{ product.price }} ron</p>
                        <span class="mt-auto">
                <a href="#" class="card-link">Another link</a>
            </span>
        </div>
    </div>

{% endblock %}

MiniStore/products/templates/products.html
{% extends 'main.html' %}
{% block content %}
    {% if products %}
        <div class="container mt-4" style="display: grid; grid-template-columns: repeat(4, 1fr)">
            {% for pr in products %}
                <div class="card mb-5" style="width: 18rem; height: 10rem;">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{ pr.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ pr.short_description }}</h6>
                                                <p class="card-text">{{ pr.price }} ron</p>
                        <span class="mt-auto">
                            <a href="{% url 'products:product' pr.id %}" class="card-link">See more</a>
                            <a href="{% url 'orders:add_to_cart' pr.id %}" class="card-link">Add to cart</a>
                        </span>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div>
            <p>No products available</p>
        </div>
    {% endif %}
{% if perms.products.add_product %}
        <div>
<!--            <button class="btn btn-primary" onclick="location.href = '{% url 'products:add_product' %}'">Add product-->
<!--            </button>-->
        </div>
{% endif %}
{% endblock %}

MiniStore/products/templates/products_form.html
{% extends "main.html" %}
{% load crispy_forms_filters %}


{% block content %}
    <div class="container mt-4">
        <h1 class="h1">Add new product</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Add product" class="btn btn-success"/>
    </form>

{% endblock %}

MiniStore/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>MiniStore</title>
    {% endblock %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load fontawesome_5 %}
    {% fontawesome_5_static %}
</head>
<body>
{% block navbar %}
{% endblock %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

MiniStore/templates/main.html
{% extends 'base.html' %}

{% block navbar %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'products:products' %}"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == "/" %}active{% endif %}" aria-current="page" href="{% url 'products:products' %}">Home</a>
                    </li>
                </ul>
                <button type="button" class="btn btn-primary btn-sm me-3"
                        data-mdb-toggle="tooltip"
                        title="Cart"
                        onclick="location.href='{% url 'orders:cart' %}'">
                    <i class="fas fa-shopping-cart"></i>
                </button>
                <button class="btn btn-outline-light me-4"
                        onclick="location.href='{% url 'users:logout' %}'">Logout
                </button>
            </div>
        </div>
    </nav>

{% endblock %}

{% block content %}

{% endblock %}